[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "recursive_package"
author = "xichen3"
author-email = "xichen3@microsoft.com"
home-page = "https://github.com"
classifiers = ["License :: OSI Approved :: MIT License"]

